/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface BoardFundManagerFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "createFundManager" | "deployedFunds" | "getDeployedFunds"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "FundManagerDeployed"): EventFragment;

  encodeFunctionData(
    functionFragment: "createFundManager",
    values: [AddressLike[], AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deployedFunds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeployedFunds",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createFundManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployedFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDeployedFunds",
    data: BytesLike
  ): Result;
}

export namespace FundManagerDeployedEvent {
  export type InputTuple = [
    newFund: AddressLike,
    token: AddressLike,
    boardMembers: AddressLike[]
  ];
  export type OutputTuple = [
    newFund: string,
    token: string,
    boardMembers: string[]
  ];
  export interface OutputObject {
    newFund: string;
    token: string;
    boardMembers: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BoardFundManagerFactory extends BaseContract {
  connect(runner?: ContractRunner | null): BoardFundManagerFactory;
  waitForDeployment(): Promise<this>;

  interface: BoardFundManagerFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createFundManager: TypedContractMethod<
    [_members: AddressLike[], _token: AddressLike],
    [void],
    "nonpayable"
  >;

  deployedFunds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getDeployedFunds: TypedContractMethod<[], [string[]], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createFundManager"
  ): TypedContractMethod<
    [_members: AddressLike[], _token: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deployedFunds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getDeployedFunds"
  ): TypedContractMethod<[], [string[]], "view">;

  getEvent(
    key: "FundManagerDeployed"
  ): TypedContractEvent<
    FundManagerDeployedEvent.InputTuple,
    FundManagerDeployedEvent.OutputTuple,
    FundManagerDeployedEvent.OutputObject
  >;

  filters: {
    "FundManagerDeployed(address,address,address[])": TypedContractEvent<
      FundManagerDeployedEvent.InputTuple,
      FundManagerDeployedEvent.OutputTuple,
      FundManagerDeployedEvent.OutputObject
    >;
    FundManagerDeployed: TypedContractEvent<
      FundManagerDeployedEvent.InputTuple,
      FundManagerDeployedEvent.OutputTuple,
      FundManagerDeployedEvent.OutputObject
    >;
  };
}
