/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc721Sol from "./Erc721.sol";
export type { erc721Sol };
export type { EventContract } from "./EventContract";
