/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as multiSigWalletSol from "./MultiSigWallet.sol";
export type { multiSigWalletSol };
import type * as multiSigWalletFactorySol from "./MultiSigWalletFactory.sol";
export type { multiSigWalletFactorySol };
export type { ERC20Mock } from "./ERC20Mock";
