/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as stakingSol from "./staking.sol";
export * as token1Sol from "./token1.sol";
export * as token2Sol from "./token2.sol";
