/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as multiSigWalletSol from "./MultiSigWallet.sol";
export * as multiSigWalletFactorySol from "./MultiSigWalletFactory.sol";
export { ERC20Mock__factory } from "./ERC20Mock__factory";
