/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SwapContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addLiquidity"
      | "getAmountYForX"
      | "reserveX"
      | "reserveY"
      | "swap"
      | "tokenX"
      | "tokenY"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Swap"): EventFragment;

  encodeFunctionData(
    functionFragment: "addLiquidity",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAmountYForX",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "reserveX", values?: undefined): string;
  encodeFunctionData(functionFragment: "reserveY", values?: undefined): string;
  encodeFunctionData(functionFragment: "swap", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "tokenX", values?: undefined): string;
  encodeFunctionData(functionFragment: "tokenY", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "addLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAmountYForX",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reserveX", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "reserveY", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenX", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenY", data: BytesLike): Result;
}

export namespace SwapEvent {
  export type InputTuple = [
    user: AddressLike,
    amountXIn: BigNumberish,
    amountYOut: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amountXIn: bigint,
    amountYOut: bigint
  ];
  export interface OutputObject {
    user: string;
    amountXIn: bigint;
    amountYOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SwapContract extends BaseContract {
  connect(runner?: ContractRunner | null): SwapContract;
  waitForDeployment(): Promise<this>;

  interface: SwapContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addLiquidity: TypedContractMethod<
    [_amountX: BigNumberish, _amountY: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAmountYForX: TypedContractMethod<
    [_amountX: BigNumberish],
    [bigint],
    "view"
  >;

  reserveX: TypedContractMethod<[], [bigint], "view">;

  reserveY: TypedContractMethod<[], [bigint], "view">;

  swap: TypedContractMethod<[_amountXIn: BigNumberish], [void], "nonpayable">;

  tokenX: TypedContractMethod<[], [string], "view">;

  tokenY: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addLiquidity"
  ): TypedContractMethod<
    [_amountX: BigNumberish, _amountY: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAmountYForX"
  ): TypedContractMethod<[_amountX: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "reserveX"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "reserveY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "swap"
  ): TypedContractMethod<[_amountXIn: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tokenX"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenY"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "Swap"
  ): TypedContractEvent<
    SwapEvent.InputTuple,
    SwapEvent.OutputTuple,
    SwapEvent.OutputObject
  >;

  filters: {
    "Swap(address,uint256,uint256)": TypedContractEvent<
      SwapEvent.InputTuple,
      SwapEvent.OutputTuple,
      SwapEvent.OutputObject
    >;
    Swap: TypedContractEvent<
      SwapEvent.InputTuple,
      SwapEvent.OutputTuple,
      SwapEvent.OutputObject
    >;
  };
}
