/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc721Sol from "./Erc721.sol";
export { EventContract__factory } from "./EventContract__factory";
