/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as stakingSol from "./staking.sol";
export type { stakingSol };
import type * as token1Sol from "./token1.sol";
export type { token1Sol };
import type * as token2Sol from "./token2.sol";
export type { token2Sol };
