/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as companySol from "./Company.sol";
export * as companyTokenSol from "./companyToken.sol";
export { Lock__factory } from "./Lock__factory";
