/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as charitySol from "./charity.sol";
export type { charitySol };
export type { CrowdFunding } from "./CrowdFunding";
export type { Lock } from "./Lock";
