/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as companySol from "./Company.sol";
export type { companySol };
import type * as companyTokenSol from "./companyToken.sol";
export type { companyTokenSol };
export type { Lock } from "./Lock";
