/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CompanyFundManager } from "./CompanyFundManager";
export * as factories from "./factories";
export { CompanyFundManager__factory } from "./factories/CompanyFundManager__factory";
